version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bot_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    environment:
      POSTGRES_DB: bot_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      BOT_TOKEN: bot_token
    restart: always
    depends_on:
      - db

